#!/usr/bin/bash
source /home/macierz/s175454/tomography_venv/bin/activate
export PYTHONPATH=$PYTHONPATH:/home/macierz/s175454/tomography


nohup $( \
        python ./src/run_training.py --ww=225 --wl=25 --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=0 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=1 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=2 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=3 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=4 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=0 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=1 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=2 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=3 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --multiclass --discard --batch_size=8 --epochs=50 --gpu=4 --fold=4 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
      ) &

nohup $( \
        python ./src/run_training.py --ww=225 --wl=25 --discard --batch_size=8 --epochs=50 --gpu=5 --fold=0 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --discard --batch_size=8 --epochs=50 --gpu=5 --fold=1 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --discard --batch_size=8 --epochs=50 --gpu=5 --fold=2 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --discard --batch_size=8 --epochs=50 --gpu=5 --fold=3 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --discard --batch_size=8 --epochs=50 --gpu=5 --fold=4 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --discard --batch_size=8 --epochs=50 --gpu=5 --fold=0 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --discard --batch_size=8 --epochs=50 --gpu=5 --fold=1 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --discard --batch_size=8 --epochs=50 --gpu=5 --fold=2 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --discard --batch_size=8 --epochs=50 --gpu=5 --fold=3 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
        python ./src/run_training.py --ww=225 --wl=25 --use_polar --discard --batch_size=8 --epochs=50 --gpu=5 --fold=4 --learning_rate=0.0001 --img_size=512 --metadata="/home/macierz/s175454/lits_prepared/metadata.csv" --dataset="/home/macierz/s175454/lits_prepared" --net_name=unet --loss_name=mix --seed=30 &>> global.log; \
      ) &
